# Español, Spanish, es

WORDS={}

#From Google Translate
WORDS["Login"]={5:"Iniciar sesión"}
WORDS["My Data"]={5:"Mis datos"}
WORDS["My Profile"]={5:"Mi perfil"}
WORDS["My Team"]={5:"Mi equipo"}
WORDS["My Cards"]={5:"Mis cartas"}
WORDS["My Matches"]={5:"Mis partidos"}
WORDS["Themes"]={5:"Temas"}
WORDS["Decks"]={5:"Cubiertas"}
WORDS["Cards"]={5:"Tarjetas"}
WORDS["Team-Wars"]={5:"Guerras en equipo"}
WORDS["Build-A-Card"]={5:"Construye una tarjeta"}
WORDS["Players"]={5:"Jugadores"}
WORDS["Teams"]={5:"Equipos"}
WORDS["Brackets"]={5:"Soportes"}
WORDS["Matches"]={5:"Partidos"}
WORDS["Events"]={5:"Eventos"}
WORDS["Challenge"]={5:"Desafío"}
WORDS["Downloads"]={5:"Descargas"}
WORDS["Donate"]={5:"Donar"}
WORDS["About"]={5:"Acerca de"}
WORDS["Articles"]={5:"Artículos"}
WORDS['''
	
		Here are the meta cards by tier and time frame.
		
		* Depending on the time frame, the report may be affected by challenge mode or card usage events.
		* Filter by wide range of choices!
		* Refreshed every day.
		
	''']={5:'''Aquí están las meta tarjetas por nivel y período de tiempo.

* Dependiendo del período de tiempo, el informe puede verse afectado por el modo de desafío o los eventos de uso de la tarjeta.
* ¡Filtra por una amplia gama de opciones!
* Refrescado todos los días.'''}
WORDS["CARDS"]={5:"TARJETAS"}
WORDS["Rank Range"]={5:"Rango de rango"}
WORDS["Top 250"]={5:"Top 250"}
WORDS["Top 1000"]={5:"Top 1000"}
WORDS["MMR 8500+"]={5:"MMR 8500+"}
WORDS["MMR 8000-8500"]={5:"MMR 8000-8500"}
WORDS["MMR 7500-8000"]={5:"MMR 7500-8000"}
WORDS["MMR 7000-7500"]={5:"MMR 7000-7500"}
WORDS["MMR 6500-7000"]={5:"MMR 6500-7000"}
WORDS["MMR 650-1200"]={5:"MMR 650-1200"}
WORDS["MMR 6000-6500"]={5:"MMR 6000-6500"}
WORDS["MMR 5300-6000"]={5:"MMR 5300-6000"}
WORDS["MMR 4600-5300"]={5:"MMR 4600-5300"}
WORDS["MMR 3900-4600"]={5:"MMR 3900-4600"}
WORDS["MMR 3200-3900"]={5:"MMR 3200-3900"}
WORDS["MMR 300-650"]={5:"MMR 300-650"}
WORDS["MMR 2500-3200"]={5:"MMR 2500-3200"}
WORDS["MMR 1800-2500"]={5:"MMR 1800-2500"}
WORDS["MMR 1200-1800"]={5:"MMR 1200-1800"}
WORDS["MMR 0-300"]={5:"MMR 0-300"}
WORDS["Mode"]={5:"Modo"}
WORDS["All"]={5:"Todos"}
WORDS["Ranked"]={5:"Clasificado"}
WORDS["Friendly Fight"]={5:"Lucha amistosa"}
WORDS["Team Wars"]={5:"Guerras de equipo"}
WORDS["Time Frame"]={5:"Periodo de tiempo"}
WORDS["Last 14 days"]={5:"Últimos 14 días"}
WORDS["Last 7 days"]={5:"Los últimos 7 días"}
WORDS["Last 3 days"]={5:"Últimos 3 días"}
WORDS["Last 1 day"]={5:"Último 1 día"}
WORDS["Last Patch"]={5:"Último parche"}
WORDS["Deck Theme"]={5:"Tema de la cubierta"}
WORDS["adv"]={5:"adv"}
WORDS["sci"]={5:"ciencia"}
WORDS["mys"]={5:"mis"}
WORDS["fan"]={5:"ventilador"}
WORDS["sup"]={5:"cenar"}
WORDS["neu"]={5:"neu"}
WORDS["Type"]={5:"Tipo"}
WORDS["fight"]={5:"lucha"}
WORDS["range"]={5:"rango"}
WORDS["tank"]={5:"tanque"}
WORDS["ass"]={5:"culo"}
WORDS["spell"]={5:"deletrear"}
WORDS["Cost"]={5:"Costo"}
WORDS["Rarity"]={5:"Rareza"}
WORDS["com"]={5:"com"}
WORDS["rar"]={5:"rar"}
WORDS["epi"]={5:"epi"}
WORDS["leg"]={5:"pierna"}
WORDS["Keyword"]={5:"Palabra clave"}
WORDS["warcry"]={5:"grito de guerra"}
WORDS["deathwish"]={5:"deseo de muerte"}
WORDS["charge"]={5:"cargar"}
WORDS["flying"]={5:"volador"}
WORDS["Filter"]={5:"Filtrar"}
WORDS["link"]={5:"enlace"}
WORDS["id"]={5:"carné de identidad"}
WORDS["In % of decks"]={5:"En% de cubiertas"}
WORDS["STAN OF MANY MOONS"]={5:"STAN DE MUCHAS LUNAS"}
WORDS["DARK ANGEL RED"]={5:"ROJO ÁNGEL OSCURO"}
WORDS["MECHA TIMMY"]={5:"MECHA TIMMY"}
WORDS["MEDUSA BEBE"]={5:"MEDUSA BEBE"}
WORDS["MR. HANKEY"]={5:"SEÑOR. HANKEY"}
WORDS["INCAN CRAIG"]={5:"INCAN CRAIG"}
WORDS["UNHOLY COMBUSTION"]={5:"COMBUSTIÓN PROFUNDA"}
WORDS["INUIT KENNY"]={5:"INUIT KENNY"}
WORDS["SPACE WARRIOR TOKEN"]={5:"FICHA DE GUERRERO ESPACIAL"}
WORDS["SATAN"]={5:"SATÁN"}
WORDS["LIGHTNING BOLT"]={5:"PERNO RAYO"}
WORDS["THE MASTER NINJEW"]={5:"EL MAESTRO NINJEW"}
WORDS["VISITORS"]={5:"VISITANTES"}
WORDS["ENFORCER JIMMY"]={5:"ENFORCER JIMMY"}
WORDS["SIXTH ELEMENT RANDY"]={5:"SEXTO ELEMENTO RANDY"}
WORDS["ENERGY STAFF"]={5:"PERSONAL DE ENERGÍA"}
WORDS["HERMES KENNY"]={5:"HERMES KENNY"}
WORDS["SHIELDMAIDEN WENDY"]={5:"SHIELDMAIDEN WENDY"}
WORDS["ZEN CARTMAN"]={5:"CARTMAN ZEN"}
WORDS["MIND CONTROL"]={5:"CONTROL MENTAL"}
WORDS["DRAGONSLAYER RED"]={5:"DRAGONSLAYER ROJO"}
WORDS["UNDERPANTS GNOMES"]={5:"GNOMOS BAJOS"}
WORDS["FRONTIER BRADLEY"]={5:"FRONTIER BRADLEY"}
WORDS["SIZZLER STUART"]={5:"SIZZLER STUART"}
WORDS["WITCH DOCTOR TOKEN"]={5:"FICHA DE DOCTOR BRUJA"}
WORDS["POPE TIMMY"]={5:"EL PAPA TIMMY"}
WORDS["WITCH GARRISON"]={5:"GUARDA DE BRUJAS"}
WORDS["TRANSMOGRIFY"]={5:"TRANSMOGRIFICAR"}
WORDS["ARROWSTORM"]={5:"ARROWSTORM"}
WORDS["WARBOY TWEEK"]={5:"WARBOY TWEEK"}
WORDS["CHOIRBOY BUTTERS"]={5:"MANTEQUILLAS CHOIRBOY"}
WORDS["POWER BIND"]={5:"ENLACE DE PODER"}
WORDS["HOOKHAND CLYDE"]={5:"MANO CLYDE"}
WORDS["MYSTERION"]={5:"Misterio"}
WORDS["CATAPULT TIMMY"]={5:"CATAPULT TIMMY"}
WORDS["CALL GIRL"]={5:"LLAMAR CHICA"}
WORDS["MINT-BERRY CRUNCH"]={5:"CRUJIDO DE MENTA Y BAYAS"}
WORDS["PROFESSOR CHAOS"]={5:"PROFESOR CAOS"}
WORDS["MOSQUITO"]={5:"MOSQUITO"}
WORDS["SPACE PILOT BRADLEY"]={5:"BRADLEY PILOTO ESPACIAL"}
WORDS["PALADIN BUTTERS"]={5:"MANTECA PALADIN"}
WORDS["MANBEARPIG"]={5:"HOMBRE OSO CERDO"}
WORDS["CHICKEN COOP"]={5:"GALLINERO"}
WORDS["THE AMAZINGLY RANDY"]={5:"EL INCREÍBLEMENTE RANDY"}
WORDS["BLOOD ELF BEBE"]={5:"BEBE ELF DE SANGRE"}
WORDS["ALIEN QUEEN RED"]={5:"ALIEN QUEEN ROJO"}
WORDS["THE COON"]={5:"EL COON"}
WORDS["GRAND WIZARD CARTMAN"]={5:"GRAN MAGO CARTMAN"}
WORDS["MR. SLAVE EXECUTIONER"]={5:"SEÑOR. Verdugo esclavo"}
WORDS["POCAHONTAS RANDY"]={5:"POCAHONTAS RANDY"}
WORDS["PURIFY"]={5:"PURIFICAR"}
WORDS["SORCERESS LIANE"]={5:"BRUJA LIANE"}
WORDS["RAT SWARM"]={5:"Enjambre de ratas"}
WORDS["CHAOS HAMSTERS"]={5:"HÁMSTERES DEL CAOS"}
WORDS["COCK MAGIC"]={5:"MAGIA POLLA"}
WORDS["FIREBALL"]={5:"Bola de fuego"}
WORDS["CITY WOK GUY"]={5:"CIUDAD WOK GUY"}
WORDS["TOOLSHED"]={5:"COBERTIZO PARA HERRAMIENTAS"}
WORDS["FOUR-ASSED MONKEY"]={5:"MONO DE CUATRO CULOS"}
WORDS["ALIEN DRONE"]={5:"DRONE ALIEN"}
WORDS["DOCTOR TIMOTHY"]={5:"DOCTOR TIMOTHY"}
WORDS["THUNDERBIRD"]={5:"THUNDERBIRD"}
WORDS["TERRANCE AND PHILLIP"]={5:"TERRANCE Y PHILLIP"}
WORDS["MEDICINE WOMAN SHARON"]={5:"MEDICINA MUJER SHARON"}
WORDS["MARCUS"]={5:"MARCUS"}
WORDS["CAPTAIN WENDY"]={5:"CAPITÁN WENDY"}
WORDS["GENERAL DISARRAY"]={5:"DESASTRE GENERAL"}
WORDS["DWARF KING CLYDE"]={5:"REY ENANO CLYDE"}
WORDS["JESUS"]={5:"JESÚS"}
WORDS["PRINCESS KENNY"]={5:"PRINCESA KENNY"}
WORDS["ELVEN KING BRADLEY"]={5:"ELVEN REY BRADLEY"}
WORDS["CAPTAIN DIABETES"]={5:"CAPITÁN DIABETES"}
WORDS["MR. MACKEY"]={5:"SEÑOR. MACKEY"}
WORDS["DECKHAND BUTTERS"]={5:"MANTEQUILLAS DE DECKHAND"}
WORDS["FASTPASS"]={5:"PASE RÁPIDO"}
WORDS["PIRATE SHIP TIMMY"]={5:"BARCO PIRATA TIMMY"}
WORDS["YOUTH PASTOR CRAIG"]={5:"PASTOR DE JUVENTUD CRAIG"}
WORDS["ROGUE TOKEN"]={5:"FICHA PERO"}
WORDS["SWORDSMAN GARRISON"]={5:"GUARDIA DE ESPADA"}
WORDS["BOUNTY HUNTER KYLE"]={5:"BOUNTY HUNTER KYLE"}
WORDS["SANTA CLAUS"]={5:"PAPÁ NOEL"}
WORDS["CUPID CARTMAN"]={5:"CUPID CARTMAN"}
WORDS["DWARF ENGINEER DOUGIE"]={5:"INGENIERO ENANO DOUGIE"}
WORDS["PRIEST MAXI"]={5:"SACERDOTE MAXI"}
WORDS["POISON"]={5:"VENENO"}
WORDS["REGENERATION"]={5:"REGENERACIÓN"}
WORDS["PIGEON GANG"]={5:"PANDILLA DE PALOMAS"}
WORDS["SCOUT IKE"]={5:"SCOUT IKE"}
WORDS["A.W.E.S.O.M.-O 4000"]={5:"A.W.E.S.O.M.-O 4000"}
WORDS["HUMAN KITE"]={5:"Cometa humana"}
WORDS["DOGPOO"]={5:"POPÓ DE PERRO"}
WORDS["STAN THE GREAT"]={5:"STAN EL GRANDE"}
WORDS["POWERFIST DOUGIE"]={5:"DOUGIE PODEROSO"}
WORDS["SWASHBUCKLER RED"]={5:"SWASHBUCKLER ROJO"}
WORDS["CYBORG KENNY"]={5:"CYBORG KENNY"}
WORDS["SHERIFF CARTMAN"]={5:"SHERIFF CARTMAN"}
WORDS["SUPER CRAIG"]={5:"SUPER CRAIG"}
WORDS["SUPER FART"]={5:"SUPER FART"}
WORDS["TOWELIE"]={5:"TOALLA"}
WORDS["WONDER TWEEK"]={5:"TWEEK MARAVILLOSO"}
WORDS["BIG MESQUITE MURPH"]={5:"GRAN MESQUITE MURPH"}
WORDS["ASTRONAUT BUTTERS"]={5:"MANTECA DE ASTRONAUTA"}
WORDS["LE BARD JIMMY"]={5:"LE BARD JIMMY"}
WORDS["CLASSI"]={5:"CLASSI"}
WORDS["IMP TWEEK"]={5:"IMP TWEEK"}
WORDS["SHARPSHOOTER SHELLY"]={5:"SHELLY SHARPSHOOTER"}
WORDS["STORYTELLER JIMMY"]={5:"EL CUENTADOR JIMMY"}
WORDS["HALLELUJAH"]={5:"ALELUYA"}
WORDS["PROGRAM STAN"]={5:"PROGRAMA STAN"}
WORDS["FREEZE RAY"]={5:"RAYO CONGELADO"}
WORDS["CALAMITY HEIDI"]={5:"CALAMIDAD HEIDI"}
WORDS["PRESIDENT GARRISON"]={5:"PRESIDENTE GARRISON"}
WORDS["TUPPERWARE"]={5:"TUPPERWARE"}
WORDS["BANDITA SALLY"]={5:"BANDITA SALLY"}
WORDS["KYLE OF THE DROW ELVES"]={5:"KYLE OF THE DROW ELFES"}
WORDS["ANGEL WENDY"]={5:"ÁNGEL WENDY"}
WORDS["SEXY NUN RANDY"]={5:"SEXY NUN RANDY"}
WORDS["ROBIN TWEEK"]={5:"ROBIN TWEEK"}
WORDS["HERCULES CLYDE"]={5:"HÉRCULES CLYDE"}
WORDS["SMUGGLER IKE"]={5:"Contrabandista IKE"}
WORDS["CANADIAN KNIGHT IKE"]={5:"CABALLERO CANADIENSE IKE"}
WORDS["CHOMPER"]={5:"CHOMPER"}
WORDS["BUCCANEER BEBE"]={5:"BUCCANEER BEBE"}
WORDS["ROBO BEBE"]={5:"ROBO BEBE"}
WORDS["BIG GAY AL"]={5:"GRANDE GAY AL"}
WORDS["PROPHET DOUGIE"]={5:"PROFETA DOUGIE"}
WORDS["GIZMO IKE"]={5:"GIZMO IKE"}
WORDS["ICE SNIPER WENDY"]={5:"FRANCOTIRADOR DE HIELO WENDY"}
WORDS["Name"]={5:"Nombre"}
WORDS["Last Refresh"]={5:"Última actualización"}
WORDS["Total Decks"]={5:"Total de cubiertas"}
WORDS["Rank"]={5:"Rango"}
WORDS["Login"]={5:"Iniciar sesión"}
WORDS["My Data"]={5:"Mis datos"}
WORDS["My Profile"]={5:"Mi perfil"}
WORDS["My Team"]={5:"Mi equipo"}
WORDS["My Cards"]={5:"Mis cartas"}
WORDS["My Matches"]={5:"Mis partidos"}
WORDS["Themes"]={5:"Temas"}
WORDS["Decks"]={5:"Cubiertas"}
WORDS["Cards"]={5:"Tarjetas"}
WORDS["Team-Wars"]={5:"Guerras en equipo"}
WORDS["Build-A-Card"]={5:"Construye una tarjeta"}
WORDS["Players"]={5:"Jugadores"}
WORDS["Teams"]={5:"Equipos"}
WORDS["Brackets"]={5:"Soportes"}
WORDS["Matches"]={5:"Partidos"}
WORDS["Events"]={5:"Eventos"}
WORDS["Challenge"]={5:"Desafío"}
WORDS["Downloads"]={5:"Descargas"}
WORDS["Donate"]={5:"Donar"}
WORDS["About"]={5:"Acerca de"}
WORDS["Articles"]={5:"Artículos"}
WORDS['''
	
		Here are the meta cards by tier and time frame.
		
		* Depending on the time frame, the report may be affected by challenge mode or card usage events.
		* Filter by wide range of choices!
		* Refreshed every day.
		
	''']={5:'''Aquí están las meta tarjetas por nivel y período de tiempo.

* Dependiendo del período de tiempo, el informe puede verse afectado por el modo de desafío o los eventos de uso de la tarjeta.
* ¡Filtra por una amplia gama de opciones!
* Refrescado todos los días.'''}
WORDS["CARDS"]={5:"TARJETAS"}
WORDS["Rank Range"]={5:"Rango de rango"}
WORDS["Top 250"]={5:"Top 250"}
WORDS["Top 1000"]={5:"Top 1000"}
WORDS["MMR 8500+"]={5:"MMR 8500+"}
WORDS["MMR 8000-8500"]={5:"MMR 8000-8500"}
WORDS["MMR 7500-8000"]={5:"MMR 7500-8000"}
WORDS["MMR 7000-7500"]={5:"MMR 7000-7500"}
WORDS["MMR 6500-7000"]={5:"MMR 6500-7000"}
WORDS["MMR 650-1200"]={5:"MMR 650-1200"}
WORDS["MMR 6000-6500"]={5:"MMR 6000-6500"}
WORDS["MMR 5300-6000"]={5:"MMR 5300-6000"}
WORDS["MMR 4600-5300"]={5:"MMR 4600-5300"}
WORDS["MMR 3900-4600"]={5:"MMR 3900-4600"}
WORDS["MMR 3200-3900"]={5:"MMR 3200-3900"}
WORDS["MMR 300-650"]={5:"MMR 300-650"}
WORDS["MMR 2500-3200"]={5:"MMR 2500-3200"}
WORDS["MMR 1800-2500"]={5:"MMR 1800-2500"}
WORDS["MMR 1200-1800"]={5:"MMR 1200-1800"}
WORDS["MMR 0-300"]={5:"MMR 0-300"}
WORDS["Mode"]={5:"Modo"}
WORDS["All"]={5:"Todos"}
WORDS["Ranked"]={5:"Clasificado"}
WORDS["Friendly Fight"]={5:"Lucha amistosa"}
WORDS["Team Wars"]={5:"Guerras de equipo"}
WORDS["Time Frame"]={5:"Periodo de tiempo"}
WORDS["Last 14 days"]={5:"Últimos 14 días"}
WORDS["Last 7 days"]={5:"Los últimos 7 días"}
WORDS["Last 3 days"]={5:"Últimos 3 días"}
WORDS["Last 1 day"]={5:"Último 1 día"}
WORDS["Last Patch"]={5:"Último parche"}
WORDS["Deck Theme"]={5:"Tema de la cubierta"}
WORDS["adv"]={5:"adv"}
WORDS["sci"]={5:"ciencia"}
WORDS["mys"]={5:"mis"}
WORDS["fan"]={5:"ventilador"}
WORDS["sup"]={5:"cenar"}
WORDS["neu"]={5:"neu"}
WORDS["Type"]={5:"Tipo"}
WORDS["fight"]={5:"lucha"}
WORDS["range"]={5:"rango"}
WORDS["tank"]={5:"tanque"}
WORDS["ass"]={5:"culo"}
WORDS["spell"]={5:"deletrear"}
WORDS["Cost"]={5:"Costo"}
WORDS["Rarity"]={5:"Rareza"}
WORDS["com"]={5:"com"}
WORDS["rar"]={5:"rar"}
WORDS["epi"]={5:"epi"}
WORDS["leg"]={5:"pierna"}
WORDS["Keyword"]={5:"Palabra clave"}
WORDS["warcry"]={5:"grito de guerra"}
WORDS["deathwish"]={5:"deseo de muerte"}
WORDS["charge"]={5:"cargar"}
WORDS["flying"]={5:"volador"}
WORDS["Filter"]={5:"Filtrar"}
