# 한국어, Korean, ko

WORDS={}

#From Google Translate
WORDS["Login"]={6:"로그인"}
WORDS["My Data"]={6:"내 데이터"}
WORDS["My Profile"]={6:"내 프로필"}
WORDS["My Team"]={6:"내 팀"}
WORDS["My Cards"]={6:"내 카드"}
WORDS["My Matches"]={6:"내 경기"}
WORDS["Themes"]={6:"테마"}
WORDS["Decks"]={6:"데크"}
WORDS["Cards"]={6:"카드"}
WORDS["Team-Wars"]={6:"팀 전쟁"}
WORDS["Build-A-Card"]={6:"Build-A-Card"}
WORDS["Players"]={6:"플레이어"}
WORDS["Teams"]={6:"팀"}
WORDS["Brackets"]={6:"브래킷"}
WORDS["Matches"]={6:"성냥"}
WORDS["Events"]={6:"이벤트"}
WORDS["Challenge"]={6:"도전"}
WORDS["Downloads"]={6:"다운로드"}
WORDS["Donate"]={6:"기부"}
WORDS["About"]={6:"약"}
WORDS["Articles"]={6:"조항"}
WORDS['''
	
		Here are the meta cards by tier and time frame.
		
		* Depending on the time frame, the report may be affected by challenge mode or card usage events.
		* Filter by wide range of choices!
		* Refreshed every day.
		
	''']={6:'''다음은 계층 및 시간 프레임 별 메타 카드입니다.

* 기간에 따라 챌린지 모드 또는 카드 사용 이벤트의 영향을받을 수 있습니다.
* 다양한 선택으로 필터링하십시오!
* 매일 새로 고침.'''}
WORDS["CARDS"]={6:"카드"}
WORDS["Rank Range"]={6:"순위 범위"}
WORDS["Top 250"]={6:"상위 250 개"}
WORDS["Top 1000"]={6:"상위 1000 개"}
WORDS["MMR 8500+"]={6:"MMR 8500 이상"}
WORDS["MMR 8000-8500"]={6:"MMR 8000-8500"}
WORDS["MMR 7500-8000"]={6:"MMR 7500-8000"}
WORDS["MMR 7000-7500"]={6:"MMR 7000-7500"}
WORDS["MMR 6500-7000"]={6:"MMR 6500-7000"}
WORDS["MMR 650-1200"]={6:"MMR 650-1200"}
WORDS["MMR 6000-6500"]={6:"MMR 6000-6500"}
WORDS["MMR 5300-6000"]={6:"MMR 5300-6000"}
WORDS["MMR 4600-5300"]={6:"MMR 4600-5300"}
WORDS["MMR 3900-4600"]={6:"MMR 3900-4600"}
WORDS["MMR 3200-3900"]={6:"MMR 3200-3900"}
WORDS["MMR 300-650"]={6:"MMR 300-650"}
WORDS["MMR 2500-3200"]={6:"MMR 2500-3200"}
WORDS["MMR 1800-2500"]={6:"MMR 1800-2500"}
WORDS["MMR 1200-1800"]={6:"MMR 1200-1800"}
WORDS["MMR 0-300"]={6:"MMR 0-300"}
WORDS["Mode"]={6:"방법"}
WORDS["All"]={6:"모두"}
WORDS["Ranked"]={6:"순위"}
WORDS["Friendly Fight"]={6:"친절한 싸움"}
WORDS["Team Wars"]={6:"팀 전쟁"}
WORDS["Time Frame"]={6:"시간 프레임"}
WORDS["Last 14 days"]={6:"지난 14 일"}
WORDS["Last 7 days"]={6:"지난 7 일"}
WORDS["Last 3 days"]={6:"지난 3 일"}
WORDS["Last 1 day"]={6:"지난 1 일"}
WORDS["Last Patch"]={6:"마지막 패치"}
WORDS["Deck Theme"]={6:"덱 테마"}
WORDS["adv"]={6:"adv"}
WORDS["sci"]={6:"공상 과학"}
WORDS["mys"]={6:"mys"}
WORDS["fan"]={6:"부채"}
WORDS["sup"]={6:"저녁을 먹다"}
WORDS["neu"]={6:"뉴"}
WORDS["Type"]={6:"유형"}
WORDS["fight"]={6:"싸움"}
WORDS["range"]={6:"범위"}
WORDS["tank"]={6:"탱크"}
WORDS["ass"]={6:"나귀"}
WORDS["spell"]={6:"주문"}
WORDS["Cost"]={6:"비용"}
WORDS["Rarity"]={6:"희박"}
WORDS["com"]={6:"com"}
WORDS["rar"]={6:"rar"}
WORDS["epi"]={6:"에피"}
WORDS["leg"]={6:"다리"}
WORDS["Keyword"]={6:"예어"}
WORDS["warcry"]={6:"전쟁"}
WORDS["deathwish"]={6:"죽음의 소원"}
WORDS["charge"]={6:"요금"}
WORDS["flying"]={6:"나는"}
WORDS["Filter"]={6:"필터"}
WORDS["link"]={6:"링크"}
WORDS["id"]={6:"신분증"}
WORDS["In % of decks"]={6:"데크의 %"}
WORDS["STAN OF MANY MOONS"]={6:"많은 달의 행진"}
WORDS["DARK ANGEL RED"]={6:"다크 엔젤 레드"}
WORDS["MECHA TIMMY"]={6:"메카 티미"}
WORDS["MEDUSA BEBE"]={6:"메두사 베베"}
WORDS["MR. HANKEY"]={6:"씨. 행키"}
WORDS["INCAN CRAIG"]={6:"잉카 크레이그"}
WORDS["UNHOLY COMBUSTION"]={6:"불결한 연소"}
WORDS["INUIT KENNY"]={6:"이누이트 케니"}
WORDS["SPACE WARRIOR TOKEN"]={6:"스페이스 워리어 토큰"}
WORDS["SATAN"]={6:"사탄"}
WORDS["LIGHTNING BOLT"]={6:"번갯불"}
WORDS["THE MASTER NINJEW"]={6:"마스터 NINJEW"}
WORDS["VISITORS"]={6:"방문자"}
WORDS["ENFORCER JIMMY"]={6:"지미 강화"}
WORDS["SIXTH ELEMENT RANDY"]={6:"여섯 번째 요소 RANDY"}
WORDS["ENERGY STAFF"]={6:"에너지 직원"}
WORDS["HERMES KENNY"]={6:"헤르메스 케니"}
WORDS["SHIELDMAIDEN WENDY"]={6:"실드 맨 웬디"}
WORDS["ZEN CARTMAN"]={6:"젠 카트 맨"}
WORDS["MIND CONTROL"]={6:"마인드 컨트롤"}
WORDS["DRAGONSLAYER RED"]={6:"드래곤 슬레이어 레드"}
WORDS["UNDERPANTS GNOMES"]={6:"언더 팬츠 그놈"}
WORDS["FRONTIER BRADLEY"]={6:"FRONTIER BRADLEY"}
WORDS["SIZZLER STUART"]={6:"SIZZLER STUART"}
WORDS["WITCH DOCTOR TOKEN"]={6:"마녀 의사 토큰"}
WORDS["POPE TIMMY"]={6:"똥 티미"}
WORDS["WITCH GARRISON"]={6:"마녀 개리슨"}
WORDS["TRANSMOGRIFY"]={6:"트랜스 모 그래피"}
WORDS["ARROWSTORM"]={6:"화살 폭풍"}
WORDS["WARBOY TWEEK"]={6:"워보이 트 위크"}
WORDS["CHOIRBOY BUTTERS"]={6:"합창단 버터"}
WORDS["POWER BIND"]={6:"파워 바인드"}
WORDS["HOOKHAND CLYDE"]={6:"HOOKHAND CLYDE"}
WORDS["MYSTERION"]={6:"신비"}
WORDS["CATAPULT TIMMY"]={6:"CATAPULT TIMMY"}
WORDS["CALL GIRL"]={6:"매춘부"}
WORDS["MINT-BERRY CRUNCH"]={6:"민트 베리 크런치"}
WORDS["PROFESSOR CHAOS"]={6:"카오스 교수"}
WORDS["MOSQUITO"]={6:"모기"}
WORDS["SPACE PILOT BRADLEY"]={6:"우주 파일럿 브래들리"}
WORDS["PALADIN BUTTERS"]={6:"팔라딘 버터"}
WORDS["MANBEARPIG"]={6:"MANBEARPIG"}
WORDS["CHICKEN COOP"]={6:"닭장"}
WORDS["THE AMAZINGLY RANDY"]={6:"놀랍도록 RANDY"}
WORDS["BLOOD ELF BEBE"]={6:"블러드 엘프 베베"}
WORDS["ALIEN QUEEN RED"]={6:"외계인 퀸 레드"}
WORDS["THE COON"]={6:"쿤"}
WORDS["GRAND WIZARD CARTMAN"]={6:"그랜드 위자드 카트 맨"}
WORDS["MR. SLAVE EXECUTIONER"]={6:"씨. 노예 집행자"}
WORDS["POCAHONTAS RANDY"]={6:"포카 혼 타스 랜디"}
WORDS["PURIFY"]={6:"정화"}
WORDS["SORCERESS LIANE"]={6:"마술사 리안"}
WORDS["RAT SWARM"]={6:"쥐 떼"}
WORDS["CHAOS HAMSTERS"]={6:"카오스 햄스터"}
WORDS["COCK MAGIC"]={6:"수탉 마법"}
WORDS["FIREBALL"]={6:"화구"}
WORDS["CITY WOK GUY"]={6:"시티 WOK GUY"}
WORDS["TOOLSHED"]={6:"툴 쉐드"}
WORDS["FOUR-ASSED MONKEY"]={6:"네 마리의 원숭이"}
WORDS["ALIEN DRONE"]={6:"외계인 드론"}
WORDS["DOCTOR TIMOTHY"]={6:"의사 티모시"}
WORDS["THUNDERBIRD"]={6:"천둥새"}
WORDS["TERRANCE AND PHILLIP"]={6:"테라스와 필립"}
WORDS["MEDICINE WOMAN SHARON"]={6:"의학 여자 샤론"}
WORDS["MARCUS"]={6:"마커스"}
WORDS["CAPTAIN WENDY"]={6:"캡틴 웬디"}
WORDS["GENERAL DISARRAY"]={6:"일반적인 혼란"}
WORDS["DWARF KING CLYDE"]={6:"드워프 킹 클라이드"}
WORDS["JESUS"]={6:"예수"}
WORDS["PRINCESS KENNY"]={6:"프린세스 케니"}
WORDS["ELVEN KING BRADLEY"]={6:"엘븐 킹 브레들리"}
WORDS["CAPTAIN DIABETES"]={6:"캡틴 당뇨병"}
WORDS["MR. MACKEY"]={6:"씨. 맥키"}
WORDS["DECKHAND BUTTERS"]={6:"데크 핸드 버터"}
WORDS["FASTPASS"]={6:"빠른 패스"}
WORDS["PIRATE SHIP TIMMY"]={6:"해적선 티미"}
WORDS["YOUTH PASTOR CRAIG"]={6:"청소년 목사 크레이그"}
WORDS["ROGUE TOKEN"]={6:"ROGUE 토큰"}
WORDS["SWORDSMAN GARRISON"]={6:"검객 개리슨"}
WORDS["BOUNTY HUNTER KYLE"]={6:"바운티 헌터 카일"}
WORDS["SANTA CLAUS"]={6:"산타 클로스"}
WORDS["CUPID CARTMAN"]={6:"큐피드 카트 맨"}
WORDS["DWARF ENGINEER DOUGIE"]={6:"드워프 엔지니어 듀기"}
WORDS["PRIEST MAXI"]={6:"프리스트 맥시"}
WORDS["POISON"]={6:"독"}
WORDS["REGENERATION"]={6:"재건"}
WORDS["PIGEON GANG"]={6:"피 건강"}
WORDS["SCOUT IKE"]={6:"스카웃 IKE"}
WORDS["A.W.E.S.O.M.-O 4000"]={6:"A.W.E.S.O.M.-O 4000"}
WORDS["HUMAN KITE"]={6:"휴먼 키트"}
WORDS["DOGPOO"]={6:"DOGPOO"}
WORDS["STAN THE GREAT"]={6:"위대함"}
WORDS["POWERFIST DOUGIE"]={6:"파워 피스트 듀기"}
WORDS["SWASHBUCKLER RED"]={6:"SWASHBUCKLER RED"}
WORDS["CYBORG KENNY"]={6:"CYBORG KENNY"}
WORDS["SHERIFF CARTMAN"]={6:"보안관 카트 맨"}
WORDS["SUPER CRAIG"]={6:"슈퍼 크레이그"}
WORDS["SUPER FART"]={6:"슈퍼 방귀"}
WORDS["TOWELIE"]={6:"수건"}
WORDS["WONDER TWEEK"]={6:"원더 트 위크"}
WORDS["BIG MESQUITE MURPH"]={6:"큰 메스 퀴트 머프"}
WORDS["ASTRONAUT BUTTERS"]={6:"아스트로 노트 버터"}
WORDS["LE BARD JIMMY"]={6:"르 바드 지미"}
WORDS["CLASSI"]={6:"CLASSI"}
WORDS["IMP TWEEK"]={6:"IMP 트 위크"}
WORDS["SHARPSHOOTER SHELLY"]={6:"샤프 슈터 쉘리"}
WORDS["STORYTELLER JIMMY"]={6:"스토리 텔러 지미"}
WORDS["HALLELUJAH"]={6:"할렐루야"}
WORDS["PROGRAM STAN"]={6:"프로그램 스탠"}
WORDS["FREEZE RAY"]={6:"동결 광선"}
WORDS["CALAMITY HEIDI"]={6:"재해 HEIDI"}
WORDS["PRESIDENT GARRISON"]={6:"개리슨 회장"}
WORDS["TUPPERWARE"]={6:"TUPPERWARE"}
WORDS["BANDITA SALLY"]={6:"반디 타 샐리"}
WORDS["KYLE OF THE DROW ELVES"]={6:"DROW ELVES의 카일"}
WORDS["ANGEL WENDY"]={6:"천사 웬디"}
WORDS["SEXY NUN RANDY"]={6:"섹시 수녀 랜디"}
WORDS["ROBIN TWEEK"]={6:"로빈 트 위크"}
WORDS["HERCULES CLYDE"]={6:"헤라클레스 클라이드"}
WORDS["SMUGGLER IKE"]={6:"스 머글 러 아이크"}
WORDS["CANADIAN KNIGHT IKE"]={6:"캐나다 기사 IKE"}
WORDS["CHOMPER"]={6:"CHOMPER"}
WORDS["BUCCANEER BEBE"]={6:"BUCCANEER BEBE"}
WORDS["ROBO BEBE"]={6:"로보 베베"}
WORDS["BIG GAY AL"]={6:"빅 게이 알"}
WORDS["PROPHET DOUGIE"]={6:"예언자 듀기"}
WORDS["GIZMO IKE"]={6:"GIZMO IKE"}
WORDS["ICE SNIPER WENDY"]={6:"아이스 스나이퍼 웬디"}
WORDS["Name"]={6:"이름"}
WORDS["Last Refresh"]={6:"마지막 새로 고침"}
WORDS["Total Decks"]={6:"총 덱"}
WORDS["Rank"]={6:"계급"}
