# translate.py
# Created 04/14/20
# Updated 04/15/20
# Current Version: 0.01
# Keys:
# * EN = English
# * RU = Pусский

WORDS=dict()
#WORDS[<word>] = { <key1> : <translation1>, <key2> : <translation2>, ... }

#Navigation
WORDS["News"]={"RU":""}
WORDS["Decks"]={"RU":""}
WORDS["Themes"]={"RU":""}
WORDS["Cards"]={"RU":""}
WORDS["Teams"]={"RU":""}
WORDS["Players"]={"RU":""}
WORDS["Brackets"]={"RU":""}
WORDS["Downloads"]={"RU":""}
WORDS["Donate"]={"RU":""}
WORDS["About"]={"RU":""}
WORDS["Data"]={"RU":""}
WORDS["My"]={"RU":""}
WORDS["Team"]={"RU":""}
WORDS["Login"]={"RU":""}
WORDS["Gold"]={"RU":""}
WORDS["Silver"]={"RU":""}
WORDS["Bronze"]={"RU":""}
WORDS["Wood"]={"RU":""}
WORDS["Team Wars"]={"RU":""}
WORDS["Team Events"]={"RU":""}
WORDS["Requests"]={"RU":""}
WORDS["Applications"]={"RU":""}
WORDS["Vote"]={"RU":""}
WORDS["Upgrade"]={"RU":""}
WORDS["Battle"]={"RU":""}
WORDS["Summary"]={"RU":""}
WORDS["History"]={"RU":""}
WORDS["Requested"]={"RU":""}
WORDS["Donated"]={"RU":""}
WORDS["Queue"]={"RU":""}

#Tables
WORDS["Filter"]={"RU":""}
WORDS["Rank"]={"RU":""}
WORDS["Last"]={"RU":""}
WORDS["Refresh"]={"RU":""}
WORDS["Total"]={"RU":""}
WORDS["Day"]={"RU":""}
WORDS["In % of decks"]={"RU":""}
WORDS["Trend"]={"RU":""}
WORDS["Score"]={"RU":""}
WORDS["Country"]={"RU":""}
WORDS["Members"]={"RU":""}
WORDS["Status"]={"RU":""}
WORDS["Min NK Level"]={"RU":""}
WORDS["MMR"]={"RU":""}
WORDS["NK"]={"RU":""}
WORDS["Donated"]={"RU":""}
WORDS["TW"]={"RU":""}
WORDS["Caps"]={"RU":""}
WORDS["PVP"]={"RU":""}
WORDS["Perfect"]={"RU":""}
WORDS["CHLG"]={"RU":""}
WORDS["FF"]={"RU":""}
WORDS["Team"]={"RU":""}
WORDS["Name"]={"RU":""}
WORDS["Runs"]={"RU":""}
WORDS["Average"]={"RU":""}
WORDS["Projected"]={"RU":""}
WORDS["Maximum"]={"RU":""}
WORDS["Role"]={"RU":""}
WORDS["elder"]={"RU":""}
WORDS["regular"]={"RU":""}
WORDS["co_leader"]={"RU":""}
WORDS["leader"]={"RU":""}
WORDS["Join Date"]={"RU":""}
WORDS["Collection"]={"RU":""}
WORDS["N/A"]={"RU":""} #Abbreviation for: Not Applicable
WORDS["League"]={"RU":""} #Example: Gold, Silver, Bronze TVT League
WORDS["Description"]={"RU":""}

#Keywords
WORDS["Theme"]={"RU":"Темы"}
WORDS["Adventure"]={"RU":"Приключение"}
WORDS["Fantasy"]={"RU":"Фэнтэзи"}
WORDS["Neutral"]={"RU":"Нейтральная"}
WORDS["Mystical"]={"RU":"Мистика"}
WORDS["Sci-Fi"]={"RU":"Научно-Фантастическая"}
WORDS["Superhero"]={"RU":"Супергерои"}
WORDS["adv"]={"RU":""}
WORDS["fan"]={"RU":""}
WORDS["neu"]={"RU":""}
WORDS["mys"]={"RU":""}
WORDS["sci"]={"RU":""}
WORDS["sup"]={"RU":""}
 
WORDS["Rarity"]={"RU":"Редкость"}
WORDS["Common"]={"RU":"Обычная"}
WORDS["Rare"]={"RU":"Редкая"}
WORDS["Epic"]={"RU":"Эпическая"}
WORDS["Legendary"]={"RU":"Легендарная"}
WORDS["com"]={"RU":""}
WORDS["rar"]={"RU":""}
WORDS["epi"]={"RU":""}
WORDS["leg"]={"RU":""}

WORDS["Energy"]={"RU":"Энергия"}

WORDS["Type"]={"RU":""}
WORDS["Tank"]={"RU":""}
WORDS["Melee"]={"RU":""}
WORDS["Assassin"]={"RU":""}
WORDS["Ranged"]={"RU":""}
WORDS["Spell"]={"RU":""}
WORDS["Trap"]={"RU":""}

#Card Names
WORDS["A.W.E.S.O.M.-O 4000"]={"RU":"A.W.E.S.O.M.-O 4000"}
WORDS["Alien Clyde"]={"RU":""}
WORDS["Alien Drone"]={"RU":""}
WORDS["Alien Queen Red"]={"RU":""}
WORDS["Angel Wendy"]={"RU":""}
WORDS["Arrowstorm"]={"RU":""}
WORDS["Astronaut Butters"]={"RU":""}
WORDS["Bandita Sally"]={"RU":""}
WORDS["Barrel Dougie"]={"RU":""}
WORDS["Big Gay Al"]={"RU":""}
WORDS["Blood Elf Bebe"]={"RU":""}
WORDS["Bounty Hunter Kyle"]={"RU":""}
WORDS["Buccaneer Bebe"]={"RU":""}
WORDS["Calamity Heidi"]={"RU":""}
WORDS["Canadian Knight Ike"]={"RU":""}
WORDS["Captain Wendy"]={"RU":""}
WORDS["Catapult Timmy"]={"RU":""}
WORDS["Chicken Coop"]={"RU":""}
WORDS["Choirboy Butters"]={"RU":""}
WORDS["Classi"]={"RU":""}
WORDS["Cock Magic"]={"RU":""}
WORDS["Cupid Cartman"]={"RU":""}
WORDS["Cyborg Kenny"]={"RU":""}
WORDS["Dark Mage Craig"]={"RU":""}
WORDS["Deckhand Butters"]={"RU":""}
WORDS["Dogpoo"]={"RU":""}
WORDS["Dragonslayer Red"]={"RU":""}
WORDS["Dwarf Engineer Dougie"]={"RU":""}
WORDS["Dwarf King Clyde"]={"RU":""}
WORDS["Elven King Bradley"]={"RU":""}
WORDS["Energy Staff"]={"RU":""}
WORDS["Enforcer Jimmy"]={"RU":""}
WORDS["Fireball"]={"RU":""}
WORDS["Four-Assed Monkey"]={"RU":""}
WORDS["Freeze Ray"]={"RU":""}
WORDS["Friar Jimmy"]={"RU":""}
WORDS["Gizmo Ike"]={"RU":""}
WORDS["Grand Wizard Cartman"]={"RU":""}
WORDS["Gunslinger Kyle"]={"RU":""}
WORDS["Hallelujah"]={"RU":""}
WORDS["Hercules Clyde"]={"RU":""}
WORDS["Hermes Kenny"]={"RU":""}
WORDS["Hookhand Clyde"]={"RU":""}
WORDS["Hyperdrive"]={"RU":""}
WORDS["Ice Sniper Wendy"]={"RU":""}
WORDS["Imp Tweek"]={"RU":""}
WORDS["Incan Craig"]={"RU":""}
WORDS["Inuit Kenny"]={"RU":""}
WORDS["Kyle of the Drow Elves"]={"RU":""}
WORDS["Le Bard Jimmy"]={"RU":""}
WORDS["Lightning Bolt"]={"RU":""}
WORDS["Manbearpig"]={"RU":""}
WORDS["Marcus"]={"RU":""}
WORDS["Marine Craig"]={"RU":""}
WORDS["Mecha Timmy"]={"RU":""}
WORDS["Medicine Woman Sharon"]={"RU":""}
WORDS["Medusa Bebe"]={"RU":""}
WORDS["Mimsy"]={"RU":""}
WORDS["Mind Control"]={"RU":""}
WORDS["Mr. Hankey"]={"RU":""}
WORDS["Mr. Mackey"]={"RU":""}
WORDS["Mr. Slave Executioner"]={"RU":""}
WORDS["Nathan"]={"RU":""}
WORDS["Nelly"]={"RU":""}
WORDS["Officer Barbrady"]={"RU":""}
WORDS["Outlaw Tweek"]={"RU":""}
WORDS["Paladin Butters"]={"RU":""}
WORDS["PC Principal"]={"RU":""}
WORDS["Pigeon Gang"]={"RU":""}
WORDS["Pirate Ship Timmy"]={"RU":""}
WORDS["Pocahontas Randy"]={"RU":""}
WORDS["Poison"]={"RU":""}
WORDS["Pope Timmy"]={"RU":""}
WORDS["Poseidon Stan"]={"RU":""}
WORDS["Power Bind"]={"RU":""}
WORDS["Powerfist Dougie"]={"RU":""}
WORDS["Priest Maxi"]={"RU":""}
WORDS["Princess Kenny"]={"RU":""}
WORDS["Program Stan"]={"RU":""}
WORDS["Prophet Dougie"]={"RU":""}
WORDS["Purify"]={"RU":""}
WORDS["Rat Swarm"]={"RU":""}
WORDS["Regeneration"]={"RU":""}
WORDS["Robin Tweek"]={"RU":""}
WORDS["Robo Bebe"]={"RU":""}
WORDS["Rogue Token"]={"RU":""}
WORDS["Santa Claus"]={"RU":""}
WORDS["Satan"]={"RU":""}
WORDS["Scout Ike"]={"RU":""}
WORDS["Sexy Nun Randy"]={"RU":""}
WORDS["Shaman Token"]={"RU":""}
WORDS["Sharpshooter Shelly"]={"RU":""}
WORDS["Sheriff Cartman"]={"RU":""}
WORDS["Shieldmaiden Wendy"]={"RU":""}
WORDS["Sixth Element Randy"]={"RU":""}
WORDS["Smuggler Ike"]={"RU":""}
WORDS["Space Warrior Token"]={"RU":""}
WORDS["Stan of Many Moons"]={"RU":""}
WORDS["Stan the Great"]={"RU":""}
WORDS["Starvin' Marvin"]={"RU":""}
WORDS["Storyteller Jimmy"]={"RU":""}
WORDS["Swashbuckler Red"]={"RU":""}
WORDS["Swordsman Garrison"]={"RU":""}
WORDS["Terrance and Phillip"]={"RU":""}
WORDS["Terrance Mephesto"]={"RU":""}
WORDS["The Amazingly Randy"]={"RU":""}
WORDS["The Master Ninjew"]={"RU":""}
WORDS["Towelie"]={"RU":""}
WORDS["Transmogrify"]={"RU":""}
WORDS["Underpants Gnomes"]={"RU":""}
WORDS["Unholy Combustion"]={"RU":""}
WORDS["Visitors"]={"RU":""}
WORDS["Warboy Tweek"]={"RU":""}
WORDS["Witch Doctor Token"]={"RU":""}
WORDS["Witch Garrison"]={"RU":""}
WORDS["Youth Pastor Craig"]={"RU":""}
WORDS["Zen Cartman"]={"RU":""}
WORDS["Unknown"]={"RU":""}
WORDS["Fastpass"]={"RU":""}
WORDS["The Coon"]={"RU":""}
WORDS["Tupperware"]={"RU":""}
WORDS["Call Girl"]={"RU":""}
WORDS["Mosquito"]={"RU":""}
WORDS["Human Kite"]={"RU":""}
WORDS["Super Fart"]={"RU":""}
WORDS["Toolshed"]={"RU":""}
WORDS["Chomper"]={"RU":""}
WORDS["Mysterion"]={"RU":""}
WORDS["Professor Chaos"]={"RU":""}
WORDS["Lava!"]={"RU":""}
WORDS["Doctor Timothy"]={"RU":""}
WORDS["Captain Diabetes"]={"RU":""}
WORDS["Big Mesquite Murph"]={"RU":""}
WORDS["Sorceress Liane"]={"RU":""}
WORDS["President Garrison"]={"RU":""}
WORDS["Mint-Berry Crunch"]={"RU":""}
WORDS["Jesus"]={"RU":""}
WORDS["Mayor McDaniels"]={"RU":""}
WORDS["Sizzler Stuart"]={"RU":""}
WORDS["Super Craig"]={"RU":""}
WORDS["Wonder Tweek"]={"RU":""}
WORDS["ThunderBird"]={"RU":""}