# translate.py
# Created 04/14/20
# Updated 04/15/20
# Current Version: 0.01
# Keys:
# * EN = English
# * RU = Pусский

WORDS=dict()
#WORDS[<word>] = { <key1> : <translation1>, <key2> : <translation2>, ... }

#Navigation
WORDS["News"]={"RU":"Новости"}
WORDS["Decks"]={"RU":"Колоды"}
WORDS["Themes"]={"RU":"Темы"}
WORDS["Cards"]={"RU":"Карты"}
WORDS["Teams"]={"RU":"Команды"}
WORDS["Players"]={"RU":"Игроки"}
WORDS["Brackets"]={"RU":"Турнирная сетка"}
WORDS["Downloads"]={"RU":"Загрузки"}
WORDS["Donate"]={"RU":"Пожертвования"}
WORDS["About"]={"RU":"О нас"}
WORDS["Data"]={"RU":"Информация"}
WORDS["My"]={"RU":"Мои"}
WORDS["Team"]={"RU":"Команда"}
WORDS["Login"]={"RU":"Войти"}
WORDS["Gold"]={"RU":"Золотая Лига"}
WORDS["Silver"]={"RU":"Серебряная Лига"}
WORDS["Bronze"]={"RU":"Бронзовая Лига"}
WORDS["Wood"]={"RU":"Деревянная Лига"}
WORDS["Team Wars"]={"RU":"Командные Войны"}
WORDS["Team Events"]={"RU":"События"}
WORDS["Requests"]={"RU":"Запросы"}
WORDS["Applications"]={"RU":""}
WORDS["Vote"]={"RU":"Голосования"}
WORDS["Upgrade"]={"RU":"Прокачка"}
WORDS["Battle"]={"RU":"Бой"}
WORDS["Summary"]={"RU":"Общее"}
WORDS["History"]={"RU":"История"}
WORDS["Requested"]={"RU":"Запрашиваемые карты"}
WORDS["Donated"]={"RU":"Пожертвованные карты"}
WORDS["Queue"]={"RU":"Очередь"}

#Tables
WORDS["Filter"]={"RU":"Фильтры"}
WORDS["Rank"]={"RU":"Ранг"}
WORDS["Last"]={"RU":"Последний"}
WORDS["Refresh"]={"RU":"Обновить"}
WORDS["Total"]={"RU":"Общий"}
WORDS["Day"]={"RU":"Сегодня"}
WORDS["In % of decks"]={"RU":"В % колод"}
WORDS["Trend"]={"RU":"Популярные"}
WORDS["Score"]={"RU":"Счет"}
WORDS["Country"]={"RU":"Страна"}
WORDS["Members"]={"RU":"Участник"}
WORDS["Status"]={"RU":"Статус"}
WORDS["Min NK Level"]={"RU":"Мин. Ур. Новичка"}
WORDS["MMR"]={"RU":"Рейтинг"}
WORDS["NK"]={"RU":"Новичок"}
WORDS["Donated"]={"RU":"Пожертвовал"}
WORDS["TW"]={"RU":"КВ"}
WORDS["Caps"]={"RU":"Крышки"}
WORDS["PVP"]={"RU":"ПвП-бои"}
WORDS["Perfect"]={"RU":"Идеальные победы"}
WORDS["CHLG"]={"RU":"Вызовы"}
WORDS["FF"]={"RU":"Дружеский Бой"}
WORDS["Team"]={"RU":"Команда"}
WORDS["Name"]={"RU":"Ник"}
WORDS["Runs"]={"RU":"Серии"}
WORDS["Average"]={"RU":"Среднее"}
WORDS["Projected"]={"RU":"Последнее"}
WORDS["Maximum"]={"RU":"Максимум"}
WORDS["Role"]={"RU":"Должность"}
WORDS["elder"]={"RU":"Старейшина"}
WORDS["regular"]={"RU":"Участник"}
WORDS["co_leader"]={"RU":"Заместитель"}
WORDS["leader"]={"RU":"Лидер"}
WORDS["Join Date"]={"RU":"Принят в Клан"}
WORDS["Collection"]={"RU":"Список Карт"}
WORDS["N/A"]={"RU":"Неизвестно"} #Abbreviation for: Not Applicable
WORDS["League"]={"RU":"Лига"} #Example: Gold, Silver, Bronze TVT League
WORDS["Description"]={"RU":"Описание"}

#Keywords
WORDS["Theme"]={"RU":"Темы"}
WORDS["Adventure"]={"RU":"Приключение"}
WORDS["Fantasy"]={"RU":"Фэнтэзи"}
WORDS["Neutral"]={"RU":"Нейтральная"}
WORDS["Mystical"]={"RU":"Мистика"}
WORDS["Sci-Fi"]={"RU":"Научно-Фантастическая"}
WORDS["Superhero"]={"RU":"Супергерои"}
WORDS["adv"]={"RU":"Прикл."}
WORDS["fan"]={"RU":"Фэнт."}
WORDS["neu"]={"RU":"Нейтр."}
WORDS["mys"]={"RU":"Мист."}
WORDS["sci"]={"RU":"НФ"}
WORDS["sup"]={"RU":"Герои"}
 
WORDS["Rarity"]={"RU":"Редкость"}
WORDS["Common"]={"RU":"Обычная"}
WORDS["Rare"]={"RU":"Редкая"}
WORDS["Epic"]={"RU":"Эпическая"}
WORDS["Legendary"]={"RU":"Легендарная"}
WORDS["com"]={"RU":"Обыч."}
WORDS["rar"]={"RU":"Ред."}
WORDS["epi"]={"RU":"Эпич."}
WORDS["leg"]={"RU":"Лег."}

WORDS["Energy"]={"RU":"Энергия"}

WORDS["Type"]={"RU":"Тип"}
WORDS["Tank"]={"RU":"Танк"}
WORDS["Melee"]={"RU":"Боец"}
WORDS["Assassin"]={"RU":"Киллер"}
WORDS["Ranged"]={"RU":"Стрелок"}
WORDS["Spell"]={"RU":"Заклинание"}
WORDS["Trap"]={"RU":"Ловушка"}

#Card Names
WORDS["A.W.E.S.O.M.-O 4000"]={"RU":"Ш.И.К.А.Р.Н.-O 4000"}
WORDS["Alien Clyde"]={"RU":"Клайд Чужой"}
WORDS["Alien Drone"]={"RU":"Дрон Пришельцев"}
WORDS["Alien Queen Red"]={"RU":"Королева Чужих Рыжик"}
WORDS["Angel Wendy"]={"RU":"Ангел Венди"}
WORDS["Arrowstorm"]={"RU":"Ливень Стрел"}
WORDS["Astronaut Butters"]={"RU":"Космонавт Баттерс"}
WORDS["Bandita Sally"]={"RU":"Бандитка Салли"}
WORDS["Barrel Dougie"]={"RU":"Бочонок Дуги"}
WORDS["Big Gay Al"]={"RU":"Большой Эл-Гомосек"}
WORDS["Blood Elf Bebe"]={"RU":"Кровавый Эльф Биби"}
WORDS["Bounty Hunter Kyle"]={"RU":"Охотник за Головами Кайл"}
WORDS["Buccaneer Bebe"]={"RU":"Буканьер Биби"}
WORDS["Calamity Heidi"]={"RU":"Катастрофа Хайди"}
WORDS["Canadian Knight Ike"]={"RU":"Канадский Рыцарь Айк"}
WORDS["Captain Wendy"]={"RU":"Капитан Венди"}
WORDS["Catapult Timmy"]={"RU":"Катапульта Тимми"}
WORDS["Chicken Coop"]={"RU":"Курятник"}
WORDS["Choirboy Butters"]={"RU":"Певчий Баттерс"}
WORDS["Classi"]={"RU":"Классисика"}
WORDS["Cock Magic"]={"RU":"Петушинная Магия"}
WORDS["Cupid Cartman"]={"RU":"Купидон Картман"}
WORDS["Cyborg Kenny"]={"RU":"Киборг Кенни"}
WORDS["Dark Mage Craig"]={"RU":"Темный Маг Крэйг"}
WORDS["Deckhand Butters"]={"RU":"Матрос Баттерс"}
WORDS["Dogpoo"]={"RU":"Догпу"}
WORDS["Dragonslayer Red"]={"RU":"Убийца Драконов Рыжик"}
WORDS["Dwarf Engineer Dougie"]={"RU":"Гномий Инженер Дуги"}
WORDS["Dwarf King Clyde"]={"RU":"Король Гномов Клайд"}
WORDS["Elven King Bradley"]={"RU":"Король Эльфов Брэдли"}
WORDS["Energy Staff"]={"RU":"Посох Энергии"}
WORDS["Enforcer Jimmy"]={"RU":"Вышибала Джимми"}
WORDS["Fireball"]={"RU":"Огненный Шар"}
WORDS["Four-Assed Monkey"]={"RU":"Четырехжопая Обезьяна"}
WORDS["Freeze Ray"]={"RU":"Замораживающий Луч"}
WORDS["Friar Jimmy"]={"RU":"Монах Джимми"}
WORDS["Gizmo Ike"]={"RU":"Гизмо Айк"}
WORDS["Grand Wizard Cartman"]={"RU":"Великий Чародей Картман"}
WORDS["Gunslinger Kyle"]={"RU":"Стрелок Кайл"}
WORDS["Hallelujah"]={"RU":"Аллилуйя"}
WORDS["Hercules Clyde"]={"RU":"Геркулес Клайд"}
WORDS["Hermes Kenny"]={"RU":"Гермес Кенни"}
WORDS["Hookhand Clyde"]={"RU":"Клайд с Крюком"}
WORDS["Hyperdrive"]={"RU":"Гиперскорость"}
WORDS["Ice Sniper Wendy"]={"RU":"Ледяной Снайпер Венди"}
WORDS["Imp Tweek"]={"RU":"Чертенок Твик"}
WORDS["Incan Craig"]={"RU":"Инка Крэйг"}
WORDS["Inuit Kenny"]={"RU":"Эскимос Кенни"}
WORDS["Kyle of the Drow Elves"]={"RU":"Темный Эльф Кайл"}
WORDS["Le Bard Jimmy"]={"RU":"Бард Джимми"}
WORDS["Lightning Bolt"]={"RU":"Удар Молнии"}
WORDS["Manbearpig"]={"RU":"Челмедведосвин"}
WORDS["Marcus"]={"RU":"Маркус"}
WORDS["Marine Craig"]={"RU":"Морпех Крэйг"}
WORDS["Mecha Timmy"]={"RU":"Меха-Тимми"}
WORDS["Medicine Woman Sharon"]={"RU":"Женщина-Врач Шерон"}
WORDS["Medusa Bebe"]={"RU":"Медуза Биби"}
WORDS["Mimsy"]={"RU":"Мимзи"}
WORDS["Mind Control"]={"RU":"Контроль Разума"}
WORDS["Mr. Hankey"]={"RU":"Мистер Хэнки"}
WORDS["Mr. Mackey"]={"RU":"Мистер Маки"}
WORDS["Mr. Slave Executioner"]={"RU":"Мистер Мазохист"}
WORDS["Nathan"]={"RU":"Нейтан"}
WORDS["Nelly"]={"RU":"Нелли"}
WORDS["Officer Barbrady"]={"RU":"Офицер Барбреди"}
WORDS["Outlaw Tweek"]={"RU":"Разбойник Твик"}
WORDS["Paladin Butters"]={"RU":"Паладин Баттерс"}
WORDS["PC Principal"]={"RU":"ПК Директор"}
WORDS["Pigeon Gang"]={"RU":"Банда Голубей"}
WORDS["Pirate Ship Timmy"]={"RU":"Пиратский Корабль Тимми"}
WORDS["Pocahontas Randy"]={"RU":"Покахонтас Рэнди"}
WORDS["Poison"]={"RU":"Яд"}
WORDS["Pope Timmy"]={"RU":"Папа Тимми"}
WORDS["Poseidon Stan"]={"RU":"Посейдон Стэн"}
WORDS["Power Bind"]={"RU":"Блокировка Умений"}
WORDS["Powerfist Dougie"]={"RU":"Электрический Кулак Дуги"}
WORDS["Priest Maxi"]={"RU":"Священник Макси"}
WORDS["Princess Kenny"]={"RU":"Принцесса Кенни"}
WORDS["Program Stan"]={"RU":"Цифровой Стэн"}
WORDS["Prophet Dougie"]={"RU":"Пророк Дуги"}
WORDS["Purify"]={"RU":"Очищение"}
WORDS["Rat Swarm"]={"RU":"Полчище Крыс"}
WORDS["Regeneration"]={"RU":"Регенерация"}
WORDS["Robin Tweek"]={"RU":"Робин Твик"}
WORDS["Robo Bebe"]={"RU":"Робот Биби"}
WORDS["Rogue Token"]={"RU":"Разбойник Токен"}
WORDS["Santa Claus"]={"RU":"Санта Клаус"}
WORDS["Satan"]={"RU":"Сатана"}
WORDS["Scout Ike"]={"RU":"Скаут Айк"}
WORDS["Sexy Nun Randy"]={"RU":"Сексапильная Монашка Рэнди"}
WORDS["Shaman Token"]={"RU":"Шаман Токен"}
WORDS["Sharpshooter Shelly"]={"RU":"Меткий Стрелок Шелли"}
WORDS["Sheriff Cartman"]={"RU":"Шериф Картман"}
WORDS["Shieldmaiden Wendy"]={"RU":"Воительница Венди"}
WORDS["Sixth Element Randy"]={"RU":"Шестой Элемент Рэнди"}
WORDS["Smuggler Ike"]={"RU":"Контрабандист Айк"}
WORDS["Space Warrior Token"]={"RU":"Космовоитель Токен"}
WORDS["Stan of Many Moons"]={"RU":"Стэн Тысячи Лун"}
WORDS["Stan the Great"]={"RU":"Стэн Великий"}
WORDS["Starvin' Marvin"]={"RU":"Голодный Марвин"}
WORDS["Storyteller Jimmy"]={"RU":"Расказзчик Джимми"}
WORDS["Swashbuckler Red"]={"RU":"Флибустьер Рыжик"}
WORDS["Swordsman Garrison"]={"RU":"Мечник Гаррисон"}
WORDS["Terrance and Phillip"]={"RU":"Терренс и Филипп"}
WORDS["Terrance Mephesto"]={"RU":"Терренс Мефесто"}
WORDS["The Amazingly Randy"]={"RU":"Удивительный Рэнди"}
WORDS["The Master Ninjew"]={"RU":"Мастер Евредзюцу"}
WORDS["Towelie"]={"RU":"Полотенчик"}
WORDS["Transmogrify"]={"RU":"Метаморфоза"}
WORDS["Underpants Gnomes"]={"RU":"Кальсонные Гномы"}
WORDS["Unholy Combustion"]={"RU":"Нечестивый Взрыв"}
WORDS["Visitors"]={"RU":"Гости"}
WORDS["Warboy Tweek"]={"RU":"Боец Твик"}
WORDS["Witch Doctor Token"]={"RU":"Знахарь Токен"}
WORDS["Witch Garrison"]={"RU":"Ведьма Гаррисон"}
WORDS["Youth Pastor Craig"]={"RU":"Молодой Пастор Крэйг"}
WORDS["Zen Cartman"]={"RU":"Дзен Картман"}
WORDS["Unknown"]={"RU":"Неизвестно"}
WORDS["Fastpass"]={"RU":"Скороход"}
WORDS["The Coon"]={"RU":"Енот"}
WORDS["Tupperware"]={"RU":"Контейнер"}
WORDS["Call Girl"]={"RU":"Девушка по Вызову"}
WORDS["Mosquito"]={"RU":"Москит"}
WORDS["Human Kite"]={"RU":"Человек-Воздушный Змей"}
WORDS["Super Fart"]={"RU":"Суперпердеж"}
WORDS["Toolshed"]={"RU":"Инструмент"}
WORDS["Chomper"]={"RU":"Капкан"}
WORDS["Mysterion"]={"RU":"Мистерион"}
WORDS["Professor Chaos"]={"RU":"Профессор Хаос"}
WORDS["Lava!"]={"RU":"Лава!"}
WORDS["Doctor Timothy"]={"RU":"Доктор Тимоти"}
WORDS["Captain Diabetes"]={"RU":"Капитан Диабет"}
WORDS["Big Mesquite Murph"]={"RU":"Большой Мерф"}
WORDS["Sorceress Liane"]={"RU":"Колдунья Лиэн"}
WORDS["President Garrison"]={"RU":"Президент Гаррисон"}
WORDS["Mint-Berry Crunch"]={"RU":"Мятно-Ягодный Хруст}
WORDS["Jesus"]={"RU":"Иисус"}
WORDS["Mayor McDaniels"]={"RU":"Мэр МакДэниелс"}
WORDS["Sizzler Stuart"]={"RU":"Шокер Стюарт"}
WORDS["Super Craig"]={"RU":"Супер Крэйг"}
WORDS["Wonder Tweek"]={"RU":"Чудо Твик"}
WORDS["ThunderBird"]={"RU":"Буревестник"}
